namespace Gley.Localization
{
	public enum WordIDs
	{
		JokeAltitudeAchieved = 29,
		JokeBirdAsk = 26,
		JokecanRead = 34,
		JokechosenOne = 33,
		JokeDefyingGravity = 30,
		JokeFine = 39,
		JokeGravity = 41,
		JokeHouston = 31,
		JokeLvlUp = 36,
		JokeMask = 38,
		JokeMoonNextStop = 28,
		JokeProud = 35,
		JokeResponsibility = 40,
		JokesausageAstronaut = 27,
		Scene__TooLate = 25,
		Scene_BaconPeaks = 23,
		Scene_BaconPeaksSign = 22,
		Scene_EarthCall = 24,
		Scene_Grilltown = 19,
		Scene_nowhereville = 21,
		Scene_NowherevilleSign = 20,
		Scene_Wanted = 0,
		JokeSmallStep = 32,
		JokeTooHigh = 37,
		UI_Auto = 6,
		UI_Booster_perclick_desc = 9,
		UI_Booster_persec_desc = 10,
		UI_Booster_steplenght_desc = 11,
		UI_Click = 1,
		UI_Clicker = 7,
		UI_Continue = 12,
		UI_Free1 = 13,
		UI_Free2 = 14,
		UI_Free3 = 15,
		UI_GetRandom_descr = 16,
		UI_Kick = 8,
		UI_PerClick_desc = 2,
		UI_PerSec_descr = 4,
		UI_Run = 18,
		UI_StepLenght = 5,
		UI_Time = 3,
		UI_Try = 17,
	}
}